#!/usr/bin/env sh
spacebar -m config debug_output on
spacebar -m config position             top
spacebar -m config height               26

spacebar -m config text_font         "MesloLGS NF:Regular:12.0"
spacebar -m config icon_font         "MesloLGS NF:Regular:12.0"

spacebar -m config background_color  0xff121212
spacebar -m config foreground_color  0xff5cafb0
#spacebar -m config background_color  0xffe8e9ec
#spacebar -m config foreground_color  0xff33374c

spacebar -m config space_icon_strip 1 2 3 4 5 6 7 8 9

spacebar -m config right_shell        on
spacebar -m config right_shell_icon   
# spacebar -m config right_shell_command "sh ~/.config/spacebar/network.sh"

# spacebar -m config right_shell_icon   
# spacebar -m config right_shell_command "sh ~/script/cpu.sh"

spacebar -m config power_icon_strip   ⚡ ⚡
spacebar -m config space_icon         
spacebar -m config clock_icon         󰙮
spacebar -m config dnd_icon           
# spacebar -m config clock_format      "%A %B %-d %Y %R %Z"
# spacebar -m config clock_format         "%d/%m/%y %R %A"
spacebar -m config clock_format         "%d/%m/%y %A %X"

spacebar -m config left_shell         on
spacebar -m config left_shell_command "echo "Xiao"" 

